lang: es

project:
  type: book
book:
  title: "Aprendizaje Computacional"
  author:     
    - name: "Mario Graff"
      url: https://mgraffg.github.io
      affiliation: INFOTEC Centro de Investigación e Innovación en Tecnologías de la Información y Comunicación
  chapters:
    - index.qmd
    - capitulos/01Tipos.qmd
    - capitulos/02Teoria_Decision.qmd
    - capitulos/11Referencias.qmd

bibliography: references.bib
title-block-banner: false

format:
  html:
    theme: cosmo
    code-tools: true    
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto