lang: es

project:
  type: book
book:
  title: "Aprendizaje Computacional"
  author:     
    - name: "Mario Graff"
      url: https://mgraffg.github.io
      affiliation: INFOTEC Centro de Investigación e Innovación en Tecnologías de la Información y Comunicación
  chapters:
    - index.qmd
    - capitulos/01Tipos.qmd
    - capitulos/02Teoria_Decision.qmd
    - capitulos/03Parametricos.qmd
    - capitulos/04Rendimiento.qmd
    - capitulos/05ReduccionDim.qmd
    - capitulos/06Agrupamiento.qmd
    - capitulos/17Referencias.qmd
  appendices:
    - capitulos/14Estadistica.qmd
    - capitulos/15Codigo.qmd
    - capitulos/16ConjuntosDatos.qmd
  site-url: https://ingeotec.github.io/AprendizajeComputacional
  repo-url: https://github.com/INGEOTEC/AprendizajeComputacional
  downloads: pdf       

bibliography: references.bib
title-block-banner: false

format:
  html:
    theme: cosmo
    code-tools: true
    echo: true 
  pdf:
    documentclass: scrreprt
    echo: false

execute:
  freeze: auto