name: codespaces
channels:
  - conda-forge
  - defaults
dependencies:
  - IngeoML
  - seaborn
  - EvoMSA
  - wordcloud
  - pandas
  - jupyterlab
  - umap-learn
  - nltk
  - compstats
  - pip
  - pip:
    - jax
    - optax